config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    collection do
      get :home
      get :my_courses
    end
    member do
      get :buy
      post :create_order
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "courses#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy buy create_order]
  before_action :authenticate_user!, only: %i[ buy my_courses]
  skip_before_action :verify_authenticity_token, only: [:create_order]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  def home
    @courses = Course.all
  end

  def buy

  end

  def my_courses
    @courses = current_user.courses
  end

  def create_order
    UserCourse.create!(user: current_user, course: @course)
    render json: { message: "Course purchased successfully" }
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:name, :description, :image, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= course.image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= course.price %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/buy.html.erb
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= @course.name %></h6>
  </div>
  <div class="card-body">
    <%= @course.description %>
  </div>


</div>
<div id="paypal-button-container"></div>
<% content_for :javascript do %>
  <script src="https://www.paypal.com/sdk/js?client-id=AYMQBnqr7jOes4z7pJ2gp5wl_7oXEn2kaFQMVfK2khIuBEahi6bDdfz-Jmxu2gAJrwUNIUL2xxeNM8dL"></script>

  <script>
  paypal.Buttons({
    createOrder: function(data, actions) {
    return actions.order.create({
     purchase_units: [{
      amount: {
        value: "<%= @course.price %>"
      }
    }]
  });
  },
    onApprove: function(data, actions) {
      return actions.order.capture().then(function(details) {
        alert('Transaction completed by ' + details.payer.name.given_name);
        $.post('/courses/<%= @course.id %>/create_order');
      });
    }
  }).render('#paypal-button-container');
  </script>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/home.html.erb
<div class="row">

  <!-- Earnings (Monthly) Card Example -->
  <% @courses.each do |course| %>
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                <%= course.name %></div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">$<%= course.price %></div>
            </div>
            <div class="col-auto">
              <%= link_to "Buy", buy_course_path(course), class: "btn btn-primary", target: "_self"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", course %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_course_path %>

app/views/courses/my_courses.html.erb
<div class="row">

  <!-- Earnings (Monthly) Card Example -->
  <% @courses.each do |course| %>
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                <%= course.name %></div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">$<%= course.price %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails7hotwire</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="/theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/theme/css/sb-admin-2.min.css" rel="stylesheet">
  <link href="/css/tags.css" rel="stylesheet">
</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="/courses/home">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Home</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Menu
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
         aria-expanded="true" aria-controls="collapseOne">
        <i class="fas fa-fw fa-cog"></i>
        <span>Courses</span>
      </a>
      <div id="collapseOne" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Courses</h6>
          <%= link_to "All Courses", courses_path, class: 'collapse-item' %>
          <%= link_to "My Courses", my_courses_courses_path, class: 'collapse-item' %>
        </div>
      </div>
    </li>


    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

    <!-- Sidebar Message -->

  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">

    <!-- Main Content -->
    <div id="content">

      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                 aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small"
                         placeholder="Search for..." aria-label="Search"
                         aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name if user_signed_in? %></span>
              <img class="img-profile rounded-circle"
                   src="/theme/img/undraw_profile.svg">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        </ul>

      </nav>
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      <div class="container-fluid">
        <%= yield %>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    <footer class="sticky-footer bg-white">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright &copy; Your Website 2021</span>
        </div>
      </div>
    </footer>
    <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="login.html">Logout</a>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="/theme/vendor/jquery/jquery.min.js"></script>
<script src="/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/theme/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="/theme/js/sb-admin-2.min.js"></script>
<script src="/js/tags.js"></script>

<script>
  $(document).ready(function () {
      $('#tags').tagsInput();
  });
</script>
<%= yield :javascript %>

</body>
</html>